### ISSUE TITLE
Some parts of channel not working

### ISSUE THREAD

**Issue by sander1** [plexinc-plugins/PBS.bundle#24]
Videos Expiring Soon -- not working
Latest Videos -- not working
Search PBS Videos -- empty listing

**Comment by shopgirl284** [comment]
This is an old issue so I do not know how relevant but everything but the Video Search works for me now, if you include the PR I jset sent.

The video search should be easy to fix, it would use the same URL as the channel, and just pull episode info instead of show info. I just never use that part, so did not think to look into it.  

So I will give the video search a look

**Comment by shopgirl284** [comment]
See PR #26 it now has a video search that works
